[package]
name = "blockus-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.0"
palette = "0.7.6"
ratatui = { version = "0.27.0", features = ["crossterm", "palette"] }
thiserror = "1.0.61"
